name: Build And Upload Image For Release
on:
  push:
    tags:
      - v*
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract Version
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          echo VERSION_TAG=latest >> $GITHUB_ENV
          echo VERSION=${GITHUB_REF#refs/tags/v} >> $GITHUB_ENV
          echo COMMIT_ID=${GITHUB_SHA:0:7} >> $GITHUB_ENV
      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/webdav:${{ env.VERSION_TAG }}
            ${{ secrets.DOCKERHUB_USERNAME }}/webdav:${{ env.VERSION }}
          build-args: |
            VERSION=${{ env.VERSION }}
            COMMIT_ID=${{ env.COMMIT_ID }}
